export const eveData = [
  {
    id: '1',
    categoryId: '1',
    name: 'Citrine Trekeir',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 823,
    image: 'http://image.eveonline.com/Character/95040474_256.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: '124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB',
  },
  {
    id: '2',
    categoryId: '1',
    name: 'Neuro Isimazu',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 953,
    image: 'http://image.eveonline.com/Character/94136858_256.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: '124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB',
  },
  {
    id: '3',
    categoryId: '2',
    name: 'Caldari Basic Ship',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 1764,
    image: 'https://wiki.eveuniversity.org/images/5/5e/Ibis.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: '124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB',
  },
  {
    id: '4',
    categoryId: '3',
    name: 'Caldari Basic',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 2674,
    image: 'https://i.pinimg.com/originals/b7/3b/50/b73b50c44570408d5e7054e06156213c.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: '124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB',
  },
  {
    id: '5',
    categoryId: '4',
    name: 'Amarr ',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 1674,
    image: 'https://wiki.eveuniversity.org/images/b/b3/Naga.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: '124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB',
  },
  {
    id: '6',
    categoryId: '2',
    name: 'Drake',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultricies lorem odio, at laoreet tellus sodales in. Nullam maximus eros ut tortor ultricies rutrum. Aliquam euismod lacus non est egesta',
    price: 1674,
    image: 'http://www.eveonlineships.com/immagini/toolkit/RendersJpg/24698.jpg',
    cpu: '1.3GHz Apple A6',
    camera: '8mp (3264x2448)',
    size: '124.4mm x 59.2mm x 8.97mm (4.9 x 2.33 x 0.35)',
    weight: '132 grams (4.7 ounces) with battery',
    display: '4.0 326 pixel density',
    battery: '1480 mAh',
    memory: '16GB, 32GB and RAM 1 GB',
  },
];
